# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[time]
disabled=true
time_format="%T"

[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
up_to_date = "✓"
untracked = "🤷"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

# Language stuff

[dart]
format = "via [🔰 $version](bold red) "

[docker_context]
format = "via [🐋 $context](blue bold)"

[dotnet]
symbol = "🥅 "
style = "green"
heuristic = true

[java]
symbol = "☕ "

[kotlin]
symbol = "🅺 "
kotlin_binary = "kotlinc"

[kubernetes]
format = 'on [⛵ ($user on )($cluster in )$context \($namespace\)](dimmed green) '
disabled = false
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
".*/openshift-cluster/.*" = "openshift"
"gke_.*_(?P<var_cluster>[\\w-]+)" = "gke-$var_cluster"

[nodejs]
format = "via [🤖 $version](bold green) "


[python]
symbol = "🐍 "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
 
[rust]
format = "via [🦀 $version](red bold)"

 








